"""
SpecLock OpenAPI Specification Exporter.
Exports the OpenAPI 3.1 specification generated by FastAPI to static JSON and YAML files.
"""

import sys
from pathlib import Path
import json
import yaml
from fastapi.openapi.utils import get_openapi

# Ensure project root and src/ are on sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
SRC_PATH = PROJECT_ROOT / "src"
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

from api.main import app


def export_openapi() -> None:
    """Generates and writes openapi.json and openapi.yaml to the project root."""
    openapi_schema = get_openapi(
        title=app.title,
        version=app.version,
        openapi_version=app.openapi_version,
        description=app.description,
        routes=app.routes,
        tags=app.openapi_tags,
        servers=app.servers,
    )

    json_path = PROJECT_ROOT / "openapi.json"
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(openapi_schema, f, indent=2)
    print(f"Exported OpenAPI JSON to: {json_path}")

    yaml_path = PROJECT_ROOT / "openapi.yaml"
    with open(yaml_path, "w", encoding="utf-8") as f:
        yaml.dump(openapi_schema, f, sort_keys=False, default_flow_style=False)
    print(f"Exported OpenAPI YAML to: {yaml_path}")


if __name__ == "__main__":
    export_openapi()
